# Generated by Django 4.2.1 on 2023-05-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('cardID', models.CharField(max_length=20)),
                ('balance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('cardID', models.CharField(max_length=20)),
                ('topUP', models.FloatField()),
                ('orderID', models.CharField(max_length=200)),
                ('approve', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Reserv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('people', models.IntegerField()),
                ('time', models.CharField(max_length=20)),
                ('hours', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('cardID', models.CharField(max_length=20)),
                ('approve', models.BooleanField()),
            ],
        ),
    ]
