# Generated by Django 4.2.1 on 2023-05-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approveCode',
            field=models.CharField(default=3, max_length=6),
            preserve_default=False,
        ),
    ]
