# Generated by Django 4.2.1 on 2023-05-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_user_approvecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentbalance',
            name='bonus',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
